// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: reddit/reddit.proto

package reddit

import (
	date "google.golang.org/genproto/googleapis/type/date"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubRedditState int32

const (
	SubRedditState_SUBREDDITSTATE_UNSPECIFIED SubRedditState = 0
	SubRedditState_PUBLIC                     SubRedditState = 1
	SubRedditState_PRIVATE                    SubRedditState = 2
	SubRedditState_HIDDEN                     SubRedditState = 3
)

// Enum value maps for SubRedditState.
var (
	SubRedditState_name = map[int32]string{
		0: "SUBREDDITSTATE_UNSPECIFIED",
		1: "PUBLIC",
		2: "PRIVATE",
		3: "HIDDEN",
	}
	SubRedditState_value = map[string]int32{
		"SUBREDDITSTATE_UNSPECIFIED": 0,
		"PUBLIC":                     1,
		"PRIVATE":                    2,
		"HIDDEN":                     3,
	}
)

func (x SubRedditState) Enum() *SubRedditState {
	p := new(SubRedditState)
	*p = x
	return p
}

func (x SubRedditState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubRedditState) Descriptor() protoreflect.EnumDescriptor {
	return file_reddit_reddit_proto_enumTypes[0].Descriptor()
}

func (SubRedditState) Type() protoreflect.EnumType {
	return &file_reddit_reddit_proto_enumTypes[0]
}

func (x SubRedditState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubRedditState.Descriptor instead.
func (SubRedditState) EnumDescriptor() ([]byte, []int) {
	return file_reddit_reddit_proto_rawDescGZIP(), []int{0}
}

type PostState int32

const (
	PostState_POSTSTATE_UNSPECIFIED PostState = 0
	PostState_NORMAL_POST           PostState = 1
	PostState_LOCKED_POST           PostState = 2
	PostState_HIDDEN_POST           PostState = 3
)

// Enum value maps for PostState.
var (
	PostState_name = map[int32]string{
		0: "POSTSTATE_UNSPECIFIED",
		1: "NORMAL_POST",
		2: "LOCKED_POST",
		3: "HIDDEN_POST",
	}
	PostState_value = map[string]int32{
		"POSTSTATE_UNSPECIFIED": 0,
		"NORMAL_POST":           1,
		"LOCKED_POST":           2,
		"HIDDEN_POST":           3,
	}
)

func (x PostState) Enum() *PostState {
	p := new(PostState)
	*p = x
	return p
}

func (x PostState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PostState) Descriptor() protoreflect.EnumDescriptor {
	return file_reddit_reddit_proto_enumTypes[1].Descriptor()
}

func (PostState) Type() protoreflect.EnumType {
	return &file_reddit_reddit_proto_enumTypes[1]
}

func (x PostState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PostState.Descriptor instead.
func (PostState) EnumDescriptor() ([]byte, []int) {
	return file_reddit_reddit_proto_rawDescGZIP(), []int{1}
}

type CommentState int32

const (
	CommentState_COMMENTSTATE_UNSPECIFIED CommentState = 0
	CommentState_NORMAL_COMMENT           CommentState = 1
	CommentState_LOCKED_COMMENT           CommentState = 2
)

// Enum value maps for CommentState.
var (
	CommentState_name = map[int32]string{
		0: "COMMENTSTATE_UNSPECIFIED",
		1: "NORMAL_COMMENT",
		2: "LOCKED_COMMENT",
	}
	CommentState_value = map[string]int32{
		"COMMENTSTATE_UNSPECIFIED": 0,
		"NORMAL_COMMENT":           1,
		"LOCKED_COMMENT":           2,
	}
)

func (x CommentState) Enum() *CommentState {
	p := new(CommentState)
	*p = x
	return p
}

func (x CommentState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommentState) Descriptor() protoreflect.EnumDescriptor {
	return file_reddit_reddit_proto_enumTypes[2].Descriptor()
}

func (CommentState) Type() protoreflect.EnumType {
	return &file_reddit_reddit_proto_enumTypes[2]
}

func (x CommentState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommentState.Descriptor instead.
func (CommentState) EnumDescriptor() ([]byte, []int) {
	return file_reddit_reddit_proto_rawDescGZIP(), []int{2}
}

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reddit_reddit_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_reddit_reddit_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_reddit_reddit_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SubReddit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int32          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	State SubRedditState `protobuf:"varint,3,opt,name=state,proto3,enum=reddit.SubRedditState" json:"state,omitempty"` // State should never be unspecified
	Tags  []string       `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *SubReddit) Reset() {
	*x = SubReddit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reddit_reddit_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubReddit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubReddit) ProtoMessage() {}

func (x *SubReddit) ProtoReflect() protoreflect.Message {
	mi := &file_reddit_reddit_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubReddit.ProtoReflect.Descriptor instead.
func (*SubReddit) Descriptor() ([]byte, []int) {
	return file_reddit_reddit_proto_rawDescGZIP(), []int{1}
}

func (x *SubReddit) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SubReddit) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubReddit) GetState() SubRedditState {
	if x != nil {
		return x.State
	}
	return SubRedditState_SUBREDDITSTATE_UNSPECIFIED
}

func (x *SubReddit) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type Post struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              int32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title           string     `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content         string     `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	SubReddit       *SubReddit `protobuf:"bytes,4,opt,name=subReddit,proto3" json:"subReddit,omitempty"`
	VideoURL        *string    `protobuf:"bytes,5,opt,name=videoURL,proto3,oneof" json:"videoURL,omitempty"`
	ImageURL        *string    `protobuf:"bytes,6,opt,name=imageURL,proto3,oneof" json:"imageURL,omitempty"`
	Author          *User      `protobuf:"bytes,7,opt,name=author,proto3,oneof" json:"author,omitempty"`
	Score           int32      `protobuf:"varint,8,opt,name=score,proto3" json:"score,omitempty"`
	State           PostState  `protobuf:"varint,9,opt,name=state,proto3,enum=reddit.PostState" json:"state,omitempty"` // State should never be unspecified
	PublicationDate *date.Date `protobuf:"bytes,10,opt,name=publicationDate,proto3" json:"publicationDate,omitempty"`
}

func (x *Post) Reset() {
	*x = Post{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reddit_reddit_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_reddit_reddit_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_reddit_reddit_proto_rawDescGZIP(), []int{2}
}

func (x *Post) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Post) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Post) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Post) GetSubReddit() *SubReddit {
	if x != nil {
		return x.SubReddit
	}
	return nil
}

func (x *Post) GetVideoURL() string {
	if x != nil && x.VideoURL != nil {
		return *x.VideoURL
	}
	return ""
}

func (x *Post) GetImageURL() string {
	if x != nil && x.ImageURL != nil {
		return *x.ImageURL
	}
	return ""
}

func (x *Post) GetAuthor() *User {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *Post) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Post) GetState() PostState {
	if x != nil {
		return x.State
	}
	return PostState_POSTSTATE_UNSPECIFIED
}

func (x *Post) GetPublicationDate() *date.Date {
	if x != nil {
		return x.PublicationDate
	}
	return nil
}

type Comment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              int32        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content         string       `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Author          *User        `protobuf:"bytes,3,opt,name=author,proto3,oneof" json:"author,omitempty"`
	Parent          *Comment     `protobuf:"bytes,4,opt,name=parent,proto3" json:"parent,omitempty"`
	Score           int32        `protobuf:"varint,5,opt,name=score,proto3" json:"score,omitempty"`
	State           CommentState `protobuf:"varint,6,opt,name=state,proto3,enum=reddit.CommentState" json:"state,omitempty"` // State should never be unspecified
	PublicationDate *date.Date   `protobuf:"bytes,7,opt,name=publicationDate,proto3" json:"publicationDate,omitempty"`
}

func (x *Comment) Reset() {
	*x = Comment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reddit_reddit_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_reddit_reddit_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_reddit_reddit_proto_rawDescGZIP(), []int{3}
}

func (x *Comment) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Comment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Comment) GetAuthor() *User {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *Comment) GetParent() *Comment {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *Comment) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Comment) GetState() CommentState {
	if x != nil {
		return x.State
	}
	return CommentState_COMMENTSTATE_UNSPECIFIED
}

func (x *Comment) GetPublicationDate() *date.Date {
	if x != nil {
		return x.PublicationDate
	}
	return nil
}

type CreatePostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Post *Post `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
}

func (x *CreatePostRequest) Reset() {
	*x = CreatePostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reddit_reddit_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostRequest) ProtoMessage() {}

func (x *CreatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reddit_reddit_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostRequest.ProtoReflect.Descriptor instead.
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return file_reddit_reddit_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePostRequest) GetPost() *Post {
	if x != nil {
		return x.Post
	}
	return nil
}

type CreatePostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Post *Post `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
}

func (x *CreatePostResponse) Reset() {
	*x = CreatePostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reddit_reddit_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostResponse) ProtoMessage() {}

func (x *CreatePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reddit_reddit_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostResponse.ProtoReflect.Descriptor instead.
func (*CreatePostResponse) Descriptor() ([]byte, []int) {
	return file_reddit_reddit_proto_rawDescGZIP(), []int{5}
}

func (x *CreatePostResponse) GetPost() *Post {
	if x != nil {
		return x.Post
	}
	return nil
}

var File_reddit_reddit_proto protoreflect.FileDescriptor

var file_reddit_reddit_proto_rawDesc = []byte{
	0x0a, 0x13, 0x72, 0x65, 0x64, 0x64, 0x69, 0x74, 0x2f, 0x72, 0x65, 0x64, 0x64, 0x69, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x72, 0x65, 0x64, 0x64, 0x69, 0x74, 0x1a, 0x16, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x2f, 0x64, 0x61, 0x74, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x16, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x71, 0x0a,
	0x09, 0x53, 0x75, 0x62, 0x52, 0x65, 0x64, 0x64, 0x69, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2c,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e,
	0x72, 0x65, 0x64, 0x64, 0x69, 0x74, 0x2e, 0x53, 0x75, 0x62, 0x52, 0x65, 0x64, 0x64, 0x69, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x61, 0x67, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73,
	0x22, 0x85, 0x03, 0x0a, 0x04, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x2f, 0x0a, 0x09, 0x73, 0x75, 0x62,
	0x52, 0x65, 0x64, 0x64, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x72,
	0x65, 0x64, 0x64, 0x69, 0x74, 0x2e, 0x53, 0x75, 0x62, 0x52, 0x65, 0x64, 0x64, 0x69, 0x74, 0x52,
	0x09, 0x73, 0x75, 0x62, 0x52, 0x65, 0x64, 0x64, 0x69, 0x74, 0x12, 0x1f, 0x0a, 0x08, 0x76, 0x69,
	0x64, 0x65, 0x6f, 0x55, 0x52, 0x4c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08,
	0x76, 0x69, 0x64, 0x65, 0x6f, 0x55, 0x52, 0x4c, 0x88, 0x01, 0x01, 0x12, 0x1f, 0x0a, 0x08, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x55, 0x52, 0x4c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52,
	0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x52, 0x4c, 0x88, 0x01, 0x01, 0x12, 0x29, 0x0a, 0x06,
	0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x72,
	0x65, 0x64, 0x64, 0x69, 0x74, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x48, 0x02, 0x52, 0x06, 0x61, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x27, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x72,
	0x65, 0x64, 0x64, 0x69, 0x74, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x3b, 0x0a, 0x0f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x44, 0x61,
	0x74, 0x65, 0x52, 0x0f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44,
	0x61, 0x74, 0x65, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x55, 0x52, 0x4c,
	0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x52, 0x4c, 0x42, 0x09, 0x0a,
	0x07, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x22, 0x91, 0x02, 0x0a, 0x07, 0x43, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x29,
	0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x72, 0x65, 0x64, 0x64, 0x69, 0x74, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x48, 0x00, 0x52, 0x06,
	0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x12, 0x27, 0x0a, 0x06, 0x70, 0x61, 0x72,
	0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x72, 0x65, 0x64, 0x64,
	0x69, 0x74, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x70, 0x61, 0x72, 0x65,
	0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x2a, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x72, 0x65, 0x64, 0x64, 0x69, 0x74,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x3b, 0x0a, 0x0f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x65,
	0x52, 0x0f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74,
	0x65, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x22, 0x35, 0x0a, 0x11,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x20, 0x0a, 0x04, 0x70, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x72, 0x65, 0x64, 0x64, 0x69, 0x74, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x04, 0x70,
	0x6f, 0x73, 0x74, 0x22, 0x36, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x04, 0x70, 0x6f, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x72, 0x65, 0x64, 0x64, 0x69, 0x74,
	0x2e, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x04, 0x70, 0x6f, 0x73, 0x74, 0x2a, 0x55, 0x0a, 0x0e, 0x53,
	0x75, 0x62, 0x52, 0x65, 0x64, 0x64, 0x69, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x0a,
	0x1a, 0x53, 0x55, 0x42, 0x52, 0x45, 0x44, 0x44, 0x49, 0x54, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f,
	0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0a, 0x0a,
	0x06, 0x50, 0x55, 0x42, 0x4c, 0x49, 0x43, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x52, 0x49,
	0x56, 0x41, 0x54, 0x45, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x48, 0x49, 0x44, 0x44, 0x45, 0x4e,
	0x10, 0x03, 0x2a, 0x59, 0x0a, 0x09, 0x50, 0x6f, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x19, 0x0a, 0x15, 0x50, 0x4f, 0x53, 0x54, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e, 0x53,
	0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x4e, 0x4f,
	0x52, 0x4d, 0x41, 0x4c, 0x5f, 0x50, 0x4f, 0x53, 0x54, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x4c,
	0x4f, 0x43, 0x4b, 0x45, 0x44, 0x5f, 0x50, 0x4f, 0x53, 0x54, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b,
	0x48, 0x49, 0x44, 0x44, 0x45, 0x4e, 0x5f, 0x50, 0x4f, 0x53, 0x54, 0x10, 0x03, 0x2a, 0x54, 0x0a,
	0x0c, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x0a,
	0x18, 0x43, 0x4f, 0x4d, 0x4d, 0x45, 0x4e, 0x54, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e,
	0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x4e,
	0x4f, 0x52, 0x4d, 0x41, 0x4c, 0x5f, 0x43, 0x4f, 0x4d, 0x4d, 0x45, 0x4e, 0x54, 0x10, 0x01, 0x12,
	0x12, 0x0a, 0x0e, 0x4c, 0x4f, 0x43, 0x4b, 0x45, 0x44, 0x5f, 0x43, 0x4f, 0x4d, 0x4d, 0x45, 0x4e,
	0x54, 0x10, 0x02, 0x32, 0x4f, 0x0a, 0x06, 0x52, 0x65, 0x64, 0x64, 0x69, 0x74, 0x12, 0x45, 0x0a,
	0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x19, 0x2e, 0x72, 0x65,
	0x64, 0x64, 0x69, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x72, 0x65, 0x64, 0x64, 0x69, 0x74, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x20, 0x5a, 0x1e, 0x74, 0x6f, 0x6d, 0x79, 0x30, 0x30, 0x30, 0x30,
	0x30, 0x30, 0x30, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x72, 0x65, 0x64, 0x64, 0x69, 0x74, 0x2f,
	0x72, 0x65, 0x64, 0x64, 0x69, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_reddit_reddit_proto_rawDescOnce sync.Once
	file_reddit_reddit_proto_rawDescData = file_reddit_reddit_proto_rawDesc
)

func file_reddit_reddit_proto_rawDescGZIP() []byte {
	file_reddit_reddit_proto_rawDescOnce.Do(func() {
		file_reddit_reddit_proto_rawDescData = protoimpl.X.CompressGZIP(file_reddit_reddit_proto_rawDescData)
	})
	return file_reddit_reddit_proto_rawDescData
}

var file_reddit_reddit_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_reddit_reddit_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_reddit_reddit_proto_goTypes = []interface{}{
	(SubRedditState)(0),        // 0: reddit.SubRedditState
	(PostState)(0),             // 1: reddit.PostState
	(CommentState)(0),          // 2: reddit.CommentState
	(*User)(nil),               // 3: reddit.User
	(*SubReddit)(nil),          // 4: reddit.SubReddit
	(*Post)(nil),               // 5: reddit.Post
	(*Comment)(nil),            // 6: reddit.Comment
	(*CreatePostRequest)(nil),  // 7: reddit.CreatePostRequest
	(*CreatePostResponse)(nil), // 8: reddit.CreatePostResponse
	(*date.Date)(nil),          // 9: google.type.Date
}
var file_reddit_reddit_proto_depIdxs = []int32{
	0,  // 0: reddit.SubReddit.state:type_name -> reddit.SubRedditState
	4,  // 1: reddit.Post.subReddit:type_name -> reddit.SubReddit
	3,  // 2: reddit.Post.author:type_name -> reddit.User
	1,  // 3: reddit.Post.state:type_name -> reddit.PostState
	9,  // 4: reddit.Post.publicationDate:type_name -> google.type.Date
	3,  // 5: reddit.Comment.author:type_name -> reddit.User
	6,  // 6: reddit.Comment.parent:type_name -> reddit.Comment
	2,  // 7: reddit.Comment.state:type_name -> reddit.CommentState
	9,  // 8: reddit.Comment.publicationDate:type_name -> google.type.Date
	5,  // 9: reddit.CreatePostRequest.post:type_name -> reddit.Post
	5,  // 10: reddit.CreatePostResponse.post:type_name -> reddit.Post
	7,  // 11: reddit.Reddit.CreatePost:input_type -> reddit.CreatePostRequest
	8,  // 12: reddit.Reddit.CreatePost:output_type -> reddit.CreatePostResponse
	12, // [12:13] is the sub-list for method output_type
	11, // [11:12] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_reddit_reddit_proto_init() }
func file_reddit_reddit_proto_init() {
	if File_reddit_reddit_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_reddit_reddit_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reddit_reddit_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubReddit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reddit_reddit_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Post); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reddit_reddit_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Comment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reddit_reddit_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reddit_reddit_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_reddit_reddit_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_reddit_reddit_proto_msgTypes[3].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_reddit_reddit_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reddit_reddit_proto_goTypes,
		DependencyIndexes: file_reddit_reddit_proto_depIdxs,
		EnumInfos:         file_reddit_reddit_proto_enumTypes,
		MessageInfos:      file_reddit_reddit_proto_msgTypes,
	}.Build()
	File_reddit_reddit_proto = out.File
	file_reddit_reddit_proto_rawDesc = nil
	file_reddit_reddit_proto_goTypes = nil
	file_reddit_reddit_proto_depIdxs = nil
}
